import uuid from 'react-native-uuid'

export const Products = [
    {
        id:uuid.v4(),
        name:"PlayStation 5 Console",
        image:"https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6523/6523167_rd.jpg;maxHeight=640;maxWidth=550",
        description:"Console from Sony",
        price:499.99,
        countInStock:50,
        rating:4.9,
    },
    {
        id:uuid.v4(),
        name:"The Legend of Zelda: Tears of the Kingdom - Nintendo Switch",
        image:"https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6464/6464080_sd.jpg;maxHeight=640;maxWidth=550",
        description:"An epic adventure across the land and skies of Hyrule awaits in The Legend of Zelda™: Tears of the Kingdom for Nintendo Switch. The adventure is yours to create in a world fueled by your imagination. In this sequel to The Legend of Zelda: Breath of the Wild, you’ll decide your own path through the sprawling landscapes of Hyrule and the mysterious islands floating in the vast skies above. Can you harness the power of Link’s new abilities to fight back against the malevolent forces that threaten the kingdom?",
        price:69.99,
        countInStock:50,
        rating:5,
    },
    {
        id:uuid.v4(),
        name:"Motorola - Moto G 5G 256GB (2022 Unlocked) - Moonlight Gray",
        image:"https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6501/6501829_sd.jpg;maxHeight=640;maxWidth=550",
        description:"Upgrade to superfast speed with the new moto g 5G. With lightning-fast 5G connectivity, you can stream shows, play games, and video chat like never before. Discover new ways to tell your story using the 50 MP camera system with Dual Capture. Go for up to two days on a single charge with a 5000 mAh battery, and leave any power worries behind. Enjoy breathtaking ultra-wide views on a fast and fluid 6.5' 90 Hz display. And get plenty of room to hold everything with lots of storage. Move up to the next generation with moto g 5G.",
        price:199.99,
        countInStock:50,
        rating:4.2,
    },
    {
        id:uuid.v4(),
        name:"Samsung - 70” Class 7 Series LED 4K UHD Smart Tizen TV",
        image:"https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6429/6429416_sd.jpg;maxHeight=640;maxWidth=550",
        description:"Dive into our most brilliantly intense 4K experience, powered by Quantum Matrix Technology. By using precision Mini LEDs to create a wide range of color and contrast, rich details are revealed. Marvel at all that emerges from your darkest and brightest scenes thanks to 14 bit processing for deep blacks and over a billion shades of color. From daytime sports to movie night, your picture amazes in any light with AI processing that expertly upscales content to 4K and refines your Smart Hub and sound.",
        price:579.99,
        countInStock:50,
        rating:4.6,
    },
    {
        id:uuid.v4(),
        name:"Xbox Series X 1TB Console",
        image:"https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6428/6428324_sd.jpg;maxHeight=640;maxWidth=550",
        description:"Console from Microsoft",
        price:499.99,
        countInStock:50,
        rating:4.9,
    },
    {
        id:uuid.v4(),
        name:"God of War Ragnarök - PlayStation 5",
        image:"https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6523/6523243_sd.jpg;maxHeight=640;maxWidth=550",
        description:"Embark on an epic and heartfelt journey as Kratos and Atreus struggle with holding on and letting go. Against a backdrop of Norse Realms torn asunder by the fury of the Aesir, they’ve been trying their utmost to undo the end times. But despite their best efforts, Fimbulwinter presses onward. Witness the changing dynamic of the father-son relationship as they fight for survival; Atreus thirsts for knowledge to help him understand the prophecy of “Loki”, as Kratos struggles to break free of his past and be the father his son needs. See for yourself how fate will force a choice upon them: between their own safety or the safety of the realms. All the while, hostile Asgardian forces assemble… Venture through all Nine Realms towards the prophesied battle that will end the world. Vanquish Norse gods and monsters alike in fluid, expressive combat. Explore in wonder through stunning mythological landscapes.",
        price:69.99,
        countInStock:50,
        rating:4.9,
    },
    {
        id:uuid.v4(),
        name:"Google - Pixel 6a 128GB (Unlocked) - Charcoal",
        image:"https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6509/6509962_sd.jpg;maxHeight=640;maxWidth=550",
        description:"Meet Pixel 6a, the more affordable Google phone that adapts to you. Powered by Google Tensor, it’s super fast and secure. The battery lasts up to 72 hours with Extreme Battery Saver.***** The Pixel Camera captures the moment just how you experienced it. And with TitanM2 security, protection is built right in.",
        price:299,
        countInStock:50,
        rating:4.4,
    },
    {
        id:uuid.v4(),
        name:"Microsoft - Surface Laptop Go 2 - 12.4” Touch-Screen – Intel Core i5 – 8GB Memory - 128GB SSD (Latest Model) - Platinum",
        image:"https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6505/6505203_sd.jpg;maxHeight=640;maxWidth=550",
        description:"A sleek, portable Surface Laptop with 12.4' PixelSense touchscreen¹ and great typing experience with precision trackpad, plus the ports you need. Now with an improved HD camera to look your best on video calls, new Windows 11 experiences,² long battery life,³ and a performance boost for the things you love to do. With 11th Gen Intel speed for day-to-day apps, streaming, and casual gaming. It’s signature Surface style, speed, and convenient security for you and everyone in your home.",
        price:599.99,
        countInStock:50,
        rating:4.6,
    },
    {
        id:uuid.v4(),
        name:"Nintendo - Switch with Neon Blue and Neon Red Joy‑Con",
        image:"https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6522/6522225_sd.jpg;maxHeight=640;maxWidth=550",
        description:"Console from Nintendo",
        price:299.99,
        countInStock:50,
        rating:4.9,
    },
    {
        id:uuid.v4(),
        name:"Apple - iPhone 14 128GB - Midnight (Verizon)",
        image:"https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6505/6505109ld.jpg;maxHeight=640;maxWidth=550",
        description:"iPhone 14. With the most impressive dual-camera system on iPhone. Capture stunning photos in low light and bright light. Get peace of mind with groundbreaking safety features.",
        price:799.99,
        countInStock:50,
        rating:4.6,
    },
    {
        id:uuid.v4(),
        name:"Lenovo - IdeaPad Flex 5 15ITL05 2-in-1 15.6' Laptop - Intel Core i5 - with 8GB Memory - 256 GB SSD - Graphite Gray",
        image:"https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6502/6502662_sd.jpg;maxHeight=640;maxWidth=550",
        description:"The IdeaPad Flex 5 2-in-1 Laptop. Featuring fast processors, an IPS touchscreen, and a 360-degree hinge to get things done efficiently for work, home, or school. Boasting a long battery life and security assets that include a webcam privacy shutter and fingerprint reader, the IdeaPad Flex 5 2-in-1 Laptop allows you to be creative and stay on point with your tasks.",
        price:499.99,
        countInStock:50,
        rating:4.5,
    },
    {
        id:uuid.v4(),
        name:"Star Wars Jedi: Survivor - Xbox Series X",
        image:"https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6528/6528659_sd.jpg;maxHeight=640;maxWidth=550",
        description:"The story of Cal Kestis continues in Star Wars Jedi: Survivor, a third person galaxy-spanning action-adventure game from Respawn Entertainment, developed in collaboration with Lucasfilm Games. This narratively-driven, single player title picks up five years after the events of Star Wars Jedi: Fallen Order and follows Cal’s increasingly desperate fight as the galaxy descends further into darkness. Pushed to the edges of the galaxy by the Empire, Cal will find himself surrounded by threats new and familiar.",
        price:69.99,
        countInStock:50,
        rating:4.5,
    },
    {
        id:uuid.v4(),
        name:"Apple - 10.2-Inch iPad with Wi-Fi - 64GB - Space Gray",
        image:"https://pisces.bbystatic.com/image2/BestBuy_US/images/products/4901/4901809cv11d.jpg;maxHeight=640;maxWidth=550",
        description:"Powerful. Easy to use. Versatile. The new iPad has a beautiful 10.2-inch Retina display, powerful A13 Bionic chip, an Ultra Wide front camera with Center Stage, and works with Apple Pencil and the Smart Keyboard.¹ iPad lets you do more, more easily. All for an incredible value.",
        price:269.99,
        countInStock:50,
        rating:4.9,
    },
    {
        id:uuid.v4(),
        name:"Samsung - 85” Class QN90B Neo QLED 4K Smart Tizen TV",
        image:"https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6500/6500631_sd.jpg;maxHeight=640;maxWidth=550",
        description:"Dive into our most brilliantly intense 4K experience, powered by Quantum Matrix Technology. By using precision Mini LEDs to create a wide range of color and contrast, rich details are revealed. Marvel at all that emerges from your darkest and brightest scenes thanks to 14 bit processing for deep blacks and over a billion shades of color. From daytime sports to movie night, your picture amazes in any light with AI processing that expertly upscales content to 4K and refines your Smart Hub and sound.",
        price:2569.99,
        countInStock:50,
        rating:4.7,
    },

    {
        id:uuid.v4(),
        name:"MacBook Air 13.3' Laptop - Apple M1 chip - 8GB Memory - 256GB SSD (Latest Model) - Space Gray",
        image:"https://pisces.bbystatic.com/image2/BestBuy_US/images/products/5721/5721600_sd.jpg;maxHeight=640;maxWidth=550",
        description:"Apple’s thinnest and lightest notebook gets supercharged with the Apple M1 chip. Tackle your projects with the blazing-fast 8-core CPU. Take graphics-intensive apps and games to the next level with the 7-core GPU. And accelerate machine learning tasks with the 16-core Neural Engine. All with a silent, fanless design and the longest battery life ever — up to 18 hours.¹ MacBook Air. Still perfectly portable. Just a lot more powerful.",
        price:799.99,
        countInStock:50,
        rating:4.8,
    },
]